config/routes.rb
Rails.application.routes.draw do
  get 'reviews/new'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :restaurants, only: [:index, :new, :create, :show] do
    resources :reviews, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, :address, :category, presence: true
  validates :category, inclusion: { in: ["chinese", "italian", "japanese", "french", "belgian"] }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, :rating, presence: true
  validates :rating, numericality: { only_integer: true, in: (0..5) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for(restaurant) do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :category %>
  <%= f.input :phone_number %>
  <%= f.submit "Create restaurant", class: "btn btn-primary" %>
<% end %>

app/views/restaurants/index.html.erb
<h1>Restaurants#index</h1>
<p>Find me in app/views/restaurants/index.html.erb</p>

<ul>
<% @restaurants.each do |restaurant| %>
  <li><%= link_to restaurant.name, restaurant_path(restaurant) %></li>
<% end %>
</ul>

<div class="btn btn-primary ">
  <%= link_to "New restaurant", new_restaurant_path, class: "btn" %>
</div>

app/views/restaurants/new.html.erb
<h1>Restaurants#new</h1>
<p>Find me in app/views/restaurants/new.html.erb</p>

<%= render "form", restaurant: @restaurant %>

app/views/restaurants/show.html.erb
<h1>Restaurants#show</h1>
<p>Find me in app/views/restaurants/show.html.erb</p>

<%= @restaurant.name %>

<h2>Reviews</h2>
<ul class="list-group">
  <% @restaurant.reviews.each do |review| %>
    <li class="list-group-item"><%= review.content %><br><%= review.rating %>/5</li>
  <% end %>
</ul>

<div class="btn btn-primary ">
  <%= link_to "New review for #{@restaurant.name}", new_restaurant_review_path(@restaurant), class: "btn" %>
</div>

<%# <%= render "reviews/form", review: @review %>

app/views/reviews/_form.html.erb
<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :content %>
  <%= f.input :rating %>
  <%= f.submit "Submit review", class: "btn btn-primary" %>
<% end %>

app/views/reviews/new.html.erb
<h1>Reviews#new</h1>
<p>Find me in app/views/reviews/new.html.erb</p>

<%= render "form", review: @review %>